//*************************************************************************************************
//
// main.c - controls a BLDC motor and provides rudimentary serial logging
//
// Begun: 12/13/18
//
// Copyright (c) 2010-2017 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
//
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
//
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
//
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the
//   distribution.
//
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This is part of revision 2.1.4.178 of the Tiva Firmware Development Package.
//
//************************************************************************************************/

// include standard C things: (math, stdarg, stdbool, stdint, stdio, string)

// include Tivaware inc/ stuff: (hw_ints, hw_memmap, hw_timer, hw_types, hw_uart)

// include Tivaware driverlib/ stuff: (fpu, gpio, interrupt, pin_map, sysctl, systick, timer, uart)

// include Tivaware utils/uartstdio (for serial console)

// include header files you wrote for this project:

// Macros
#define MOTOR_CONTROL_FREQ // frequency of timer A0 interrupt (in Hz)
#define NUM_SAMPLES // Figure out how many samples you can fit in flash. 3 secs?

// Global variables
volatile uint16_t logData[NUM_SAMPLES]; // Stores the test data
volatile bool doneLogging;
volatile uint16_t logCount; // the number of samples logged

//*************************************************************************************************
//
// This function sets up UART0 to be used for a console to display info as the programs runs.
//
//************************************************************************************************/
void InitConsole(void)
{
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA); // Enable GPIO port A which is used for UART0 pins.
    SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0); // Enable UART0 so that we can configure the clock.
    GPIOPinConfigure(GPIO_PA0_U0RX); // pin muxing
    GPIOPinConfigure(GPIO_PA1_U0TX); // pin muxing
    GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1); // Select the alternate (UART) function$
    UARTClockSourceSet(UART0_BASE, UART_CLOCK_PIOSC); // Use the internal 16MHz oscillator as the UART$
    UARTStdioConfig(0, 115200, SysCtlClockGet()); // Initialize the UART for console I/O.
    UARTprintf("\n\nConsole on UART0 is up.\n");
}


//********************************************************************************************
//
// The interrupt handler for the periodic interrupt generated by Timer A0
//
//********************************************************************************************
void MotorControlInterruptHandler(void)
{
    // clear the timer interrupt:
    TimerIntClear(TIMER0_BASE, TIMER_TIMA_TIMEOUT);

    // if the logging array is not full, log another sample
    // and increment the number of samples logged.
    // What goes into the array?
    // get_current() returns an
    if(logCount < NUM_SAMPLES) {

        logData[logCount] = get_current() + (HallState << 12);

        // Increment the log entry counter
        logCount++;
    } else
        doneLogging = 1;

}

//*********************************************************************************************
//
// This function sets up timer A0 to generate interrupts
// at frequency specified by MOTOR_CONTROL_FREQ (#define'd above)
//
//*********************************************************************************************
void TimerBegin(void)
{
    // Enable the timer peripheral.
    // Enable processor interrupts.
    // Configure a 32-bit periodic timer.
    // Set the timer load based on MOTOR_CONTROL_FREQ
    // Setup the interrupts for the timer timeouts.
    // set the Timer 0A interrupt priority to be "low"
    // Enable timer interrupts
    // Enable the timer.
    // register the interrupt handler
    UARTprintf("Timer A0 initialized at %d Hz!\n",MOTOR_CONTROL_FREQ);
}


// Main function:
int main(void) {
    //*****************************************************************************************
    //
    // Local variable declarations
    //
    //*****************************************************************************************
    uint16_t i = 0; // counter used when writing log over serial

    //*****************************************************************************************
    //
    // Startup
    //
    //*****************************************************************************************
    doneLogging = 0;
    logCount = 0;

    // Allow interrupt handlers to use floating-point instructions,
    // at the expense of extra stack usage:
    FPULazyStackingEnable();

    // Set the clocking to run directly from the external crystal/oscillator:
    SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN | SYSCTL_XTAL_16MHZ);

    // Set up the serial console to use for displaying messages:
    InitConsole();

    // Set up PB0 (unused by DRV8323RS) as a digial output, for visualizing ISR timing:
    // (but put it in a separate function)
    // - enable GPIO port B
    // - check if peripheral access enabled
    // - enable pin PB0
    // - initialize PB0 to LOW
    UARTprintf("\t\t...PB0 initialized as a digital output.\n");


    // Set up the BLDC motor

    // Initialize the timer that will generate interrupts at MOTOR_CONTROL_FREQ

    UARTprintf("Setup complete!\n");

    // Read the Hall state once before entering the main loop
    HallState = read_halls();

    // Commutate once before entering the main loop (kickstart the motor)
    bldc_commutate(-10,HallState);

    //*****************************************************************************************
    //
    // Superloop:
    //
    //*****************************************************************************************
	while(1)
	{
        // don't do anything until done logging motor data
	    if(doneLogging) {
            // Do a safe shutdown
            // 1 - stop commutating by first disabling Hall interrupts
	        // disable Hall A interrupts
	        // disable Hall B interrupts
	        // disable Hall C interrupts

            // 2 - disable each motor phase (INLx)
            // disable phase A
            // disable phase B
            // disable phase C

	        UARTprintf("Hall state, Current(counts)\n");
	        for(i=0; i<NUM_SAMPLES; i++) {
                UARTprintf("\t%d,%d\n", (logData[i] & 0xF000) >> 12, logData[i] & 0x0FFF);
	        }
	        break;
	    }
	}
    return 0; // something, somewhere, went horribly wrong.
}
